### ISSUE TITLE
How do you fix or investigate an error when processing a ZIP file?

### ISSUE THREAD

**Issue by cmichael-de** [contao-estatemanager/core#201]
I have been using the plugin in a project for years without any known issues. Now there is an error when synchronizing a ZIP file. I can't find any indication of a faulty synchronization in the Contao log. Does the plugin write log messages? How do you deal with such a problem?

I am grateful for any tips and help!

I am using Contao EstateManager Core Version 1.0.30 together with Contao 4.13.44.

![image](https://github.com/contao-estatemanager/core/assets/6968063/456a93a6-5bed-451e-9fb0-6018f8a3e1d2)

**Comment by zoglo** [comment]
Hey @cmichael-de 

You could debug the RealEstateImporter class locally with this file and try to find out what causes the issue (in most cases, it's a wrong configuration in your system).

This could happen due to many different reasons:
- Wrong configuration in any of the interface settings
- Wrong server settings
- Wrong images
- Broken import files
- Wrong settings on any side
- And much more

I wouldn't say it's impossible to catch "every" error on any part of the import but that is way out of scope for free open source software.

If you want us to investigate your issue, you can commission us to do it for you:
https://www.contao-estatemanager.com/de/kontakt.html

**Comment by cmichael-de** [comment]
Thank you very much for your response and the helpful tips. We have recreated the object, and the transfer worked. If there are any problems again, I will be happy to contact you directly as suggested.

Best regards,

Christian
